       var substringMatcher = function (strs) {
            return function findMatches(q, cb) {
                var matches, substringRegex;

                // an array that will be populated with substring matches
                matches = [];

                // regex used to determine if a string contains the substring `q`
                substrRegex = new RegExp(q, 'i');

                // iterate through the pool of strings and for any string that
                // contains the substring `q`, add it to the `matches` array
                $.each(strs, function (i, str) {
                    if (substrRegex.test(str)) {
                        // the typeahead jQuery plugin expects suggestions to a
                        // JavaScript object, refer to typeahead docs for more info
                        matches.push({ value: str });
                    }
                });

                cb(matches);
            };
        };
        var locations = ['Acton Central',
'Acton Town',
'Aldgate',
'Aldgate East',
'All Saints',
'Alperton',
'Amersham',
'Angel',
'Archway',
'Arnos Grove',
'Arsenal',
'Baker Street',
'Balham',
'Bank',
'Barbican',
'Barking',
'Barkingside',
'Barons Court',
'Bayswater',
'Beckton',
'Beckton Park',
'Becontree',
'Belsize Park',
'Bermondsey',
'Bethnal Green',
'Blackfriars',
'Blackhorse Road',
'Blackwall',
'Bond Street',
'Borough',
'Boston Manor',
'Bounds Green',
'Bow Church',
'Bow Road',
'Brent Cross',
'Brixton',
'Bromley-by-Bow',
'Brondesbury',
'Brondesbury Park',
'Buckhurst Hill',
'Burnt Oak',
'Caledonian Road',
'Caledonian Road & Barnsbury',
'Camden Road',
'Camden Town',
'Canada Water',
'Canary Wharf',
'Canning Town',
'Cannon Street',
'Canonbury',
'Canons Park',
'Chalfont & Latimer',
'Chalk Farm',
'Chancery Lane',
'Charing Cross',
'Chesham',
'Chigwell',
'Chiswick Park',
'Chorleywood',
'Clapham Common',
'Clapham North',
'Clapham South',
'Cockfosters?',
'Colindale',
'Colliers Wood',
'Covent Garden',
'Crossharbour And London Arena',
'Croxley',
'Custom House for ExCel',
'Cutty Sark',
'Cyprus',
'Dagenham East',
'Dagenham Heathway',
'Dalston Kingsland',
'Debden',
'Debtford Bridge',
'Devons Road',
'Dollis Hill',
'Ealing Broadway',
'Ealing Common',
'Earls Court',
'East Acton',
'East Finchley',
'East Ham',
'East India',
'East Putney',
'Eastcote',
'Edgware',
'Edgware Road',
'Elephant And Castle',
'Elm Park',
'Elverson Road',
'Embankment',
'Epping',
'Euston',
'Euston Square',
'Fairlop',
'Farringdon',
'Finchley',
'Finchley Road',
'Finchley Road And Frognal',
'Finsbury Park',
'Fulham Broadway',
'Gallions Reach',
'Gants Hill',
'Gloucester Road?',
'Golders Green',
'Goldhawk Road',
'Goodge Street',
'Gospel Oak',
'Grange Hill',
'Great Portland Street',
'Green Park',
'Greenford',
'Greenwich',
'Gunnersbury',
'Hackney Central',
'Hackney Wick',
'Hainault',
'Hammersmith',
'Hampstead',
'Hampstead Heath',
'Hanger Lane',
'Harlesden',
'Harrow And Wealdstone',
'Harrow on-the-Hill',
'Hatton Cross',
'Heathrow Terminal 4',
'Heathrow Terminals 1,2,3',
'Hendon Central',
'Heron Quays',
'High Barnet',
'High Street Kensington',
'Highbury & Islington',
'Highgate',
'Hillingdon',
'Holborn',
'Holland Park',
'Holloway Road',
'Homerton',
'Hornchurch',
'Hounslow Central',
'Hounslow East',
'Hounslow West',
'Hyde Park Corner',
'Ickenham',
'Island Gardens',
'Kennington',
'Kensal Green',
'Kensal Rise',
'Kensington (Olympia)',
'Kentish Town',
'Kentish Town West',
'Kenton',
'Kew Gardens',
'Kilburn',
'Kilburn Park',
'Kings Cross St Pancras?',
'Kingsbury',
'Knightsbridge',
'Ladbroke Grove',
'Lambeth North?',
'Lancaster Gate',
'Latimer Road',
'Leicester Square',
'Lewisham',
'Leyton',
'Leytonstone',
'Limehouse',
'Liverpool Street',
'London Bridge',
'Loughton',
'Maida Vale?',
'Manor House',
'Mansion House',
'Marble Arch',
'Marylebone',
'Mile End',
'Mill Hill East',
'Monument',
'Moor Park',
'Moorgate',
'Morden',
'Mornington Crescent',
'Mudchute',
'Neasden',
'New Cross',
'New Cross Gate',
'Newbury Park',
'North Acton',
'North Ealing',
'North Greenwich',
'North Harrow',
'North Wembley',
'North Woolwich',
'Northfields',
'Northolt',
'Northwick Park',
'Northwood',
'Northwood Hills',
'Notting Hill Gate',
'Oakwood',
'Old Street',
'Osterley',
'Oval',
'Oxford Circus',
'Paddington',
'Park Royal',
'Parsons Green',
'Perivale',
'Picadilly Circus',
'Pimlico',
'Pinner',
'Plaistow',
'Poplar',
'Preston Road',
'Prince Regent',
'Pudding Mill Lane',
'Putney Bridge',
'Queens Park',
'Queensbury',
'Queensway',
'Ravenscourt Park',
'Rayners Lane',
'Redbridge',
'Regents Park',
'Richmond',
'Rickmansworth',
'Roding Valley',
'Rotherhithe',
'Royal Albert',
'Royal Oak',
'Royal Victoria',
'Ruislip',
'Ruislip Gardens',
'Ruislip Manor',
'Russel Square',
'Seven Sisters',
'Shadwell',
'Shepherds Bush?',
'Shoreditch',
'Silvertown',
'Sloane Square',
'Snaresbrook',
'South Acton',
'South Ealing',
'South Harrow',
'South Kensington',
'South Kenton',
'South Quay',
'South Ruislip',
'South Wimbledon?',
'South Woodford',
'Southfields',
'Southgate',
'Southwark',
'St Johns Wood?',
'St Pauls?',
'St. Jamess Park',
'Stamford Brook',
'Stanmore',
'Stepney Green',
'Stockwell',
'Stonebridge Park',
'Stratford',
'Sudbury Hill',
'Sudbury Town',
'Surrey Quays',
'Swiss Cottage',
'Temple',
'Theydon Bois',
'Tooting Bec',
'Tooting Broadway',
'Tottenham Court Road',
'Tottenham Hale',
'Totteridge And Whetstone',
'Tower Gateway',
'Tower Hill',
'Tufnell Park',
'Turnham Green',
'Turnpike Lane',
'Upminster',
'Upminster Bridge',
'Upney',
'Upton Park',
'Uxbridge',
'Vauxhall',
'Victoria',
'Walthamstow Central',
'Wanstead',
'Wapping',
'Warren Street',
'Warwick Avenue',
'Waterloo',
'Watford',
'Wembley Central',
'Wembley Park',
'West Acton',
'West Brompton',
'West Finchley',
'West Ham',
'West Hampstead',
'West Harrow',
'West India Quay',
'West Kensington?',
'West Ruislip',
'Westbourne Park',
'Westferry',
'Westminster',
'White City',
'Whitechapel',
'Willesden Green',
'Willesden Junction',
'Wimbledon Park',
'Wimbledon?',
'Wood Green',
'Woodford',
'Woodside Park'];

        $('.typeahead').typeahead({
            hint: true,
            highlight: true,
            minLength: 1
        },
        {
            name: 'locations',
            displayKey: 'value',
            source: substringMatcher(locations)
        });

 var mccc = window.mccc || {};

        mccc.redrawMap = function (container) {
            var target = container.find('iframe'),
                hasRedrawn = target.attr('data-has-reloaded'),
                hasMapFrame = (target.length > 0),
                mapQuery = hasMapFrame ? target.attr('data-map-query') : '';

            if (hasMapFrame && !hasRedrawn) {
                target.attr('src', 'https://maps.google.com/maps?t=m&z=15&output=embed&q=' + mapQuery).attr('data-has-reloaded', 'true');
            }
        };

        $(document).ready(function(){ 
            $('#mapAccordion').on('show.bs.collapse', function (e) {
                mccc.redrawMap($(e.target));
            });

            mccc.redrawMap($('#collapseOne'));
        });
		